# Form implementation generated from reading ui file 'addDi.ui'
#
# Created by: PyQt6 UI code generator 6.7.0.dev2404081550
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_goodsId = QtWidgets.QHBoxLayout()
        self.horizontalLayout_goodsId.setObjectName("horizontalLayout_goodsId")
        self.label_goodsId = QtWidgets.QLabel(parent=Dialog)
        self.label_goodsId.setObjectName("label_goodsId")
        self.horizontalLayout_goodsId.addWidget(self.label_goodsId)
        self.lineEdit_goodsId = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_goodsId.setObjectName("lineEdit_goodsId")
        self.horizontalLayout_goodsId.addWidget(self.lineEdit_goodsId)
        self.verticalLayout.addLayout(self.horizontalLayout_goodsId)
        self.horizontalLayout_goodsNum = QtWidgets.QHBoxLayout()
        self.horizontalLayout_goodsNum.setObjectName("horizontalLayout_goodsNum")
        self.label_goodsNum = QtWidgets.QLabel(parent=Dialog)
        self.label_goodsNum.setObjectName("label_goodsNum")
        self.horizontalLayout_goodsNum.addWidget(self.label_goodsNum)
        self.lineEdit_goodsNum = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_goodsNum.setObjectName("lineEdit_goodsNum")
        self.horizontalLayout_goodsNum.addWidget(self.lineEdit_goodsNum)
        self.verticalLayout.addLayout(self.horizontalLayout_goodsNum)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.button_confirm = QtWidgets.QPushButton(parent=Dialog)
        self.button_confirm.setObjectName("button_confirm")
        self.horizontalLayout_buttons.addWidget(self.button_confirm)
        self.button_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_buttons.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "进货"))
        self.label_goodsId.setText(_translate("Dialog", "货物ID：   "))
        self.label_goodsNum.setText(_translate("Dialog", "货物数量："))
        self.button_confirm.setText(_translate("Dialog", "确定"))
        self.button_cancel.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
