# Form implementation generated from reading ui file 'addUser.ui'
#
# Created by: PyQt6 UI code generator 6.7.0.dev2404081550
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_account = QtWidgets.QHBoxLayout()
        self.horizontalLayout_account.setObjectName("horizontalLayout_account")
        self.label_account = QtWidgets.QLabel(parent=Dialog)
        self.label_account.setObjectName("label_account")
        self.horizontalLayout_account.addWidget(self.label_account)
        self.lineEdit_account = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.horizontalLayout_account.addWidget(self.lineEdit_account)
        self.verticalLayout.addLayout(self.horizontalLayout_account)
        self.horizontalLayout_password = QtWidgets.QHBoxLayout()
        self.horizontalLayout_password.setObjectName("horizontalLayout_password")
        self.label_password = QtWidgets.QLabel(parent=Dialog)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_password.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_password.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_password)
        self.horizontalLayout_permission = QtWidgets.QHBoxLayout()
        self.horizontalLayout_permission.setObjectName("horizontalLayout_permission")
        self.label_permission = QtWidgets.QLabel(parent=Dialog)
        self.label_permission.setObjectName("label_permission")
        self.horizontalLayout_permission.addWidget(self.label_permission)
        self.comboBox_role = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_role.setObjectName("comboBox_role")
        self.comboBox_role.addItem("")
        self.comboBox_role.addItem("")
        self.horizontalLayout_permission.addWidget(self.comboBox_role)
        self.horizontalLayout_permission.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_permission)
        self.buttonLayout_role = QtWidgets.QHBoxLayout()
        self.buttonLayout_role.setObjectName("buttonLayout_role")
        self.buttonBox_OK = QtWidgets.QPushButton(parent=Dialog)
        self.buttonBox_OK.setObjectName("buttonBox_OK")
        self.buttonLayout_role.addWidget(self.buttonBox_OK)
        self.buttonBox_Cancel = QtWidgets.QPushButton(parent=Dialog)
        self.buttonBox_Cancel.setObjectName("buttonBox_Cancel")
        self.buttonLayout_role.addWidget(self.buttonBox_Cancel)
        self.verticalLayout.addLayout(self.buttonLayout_role)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加用户"))
        self.label_account.setText(_translate("Dialog", "账户:"))
        self.label_password.setText(_translate("Dialog", "密码:"))
        self.label_permission.setText(_translate("Dialog", "权限:"))
        self.comboBox_role.setItemText(0, _translate("Dialog", "管理员"))
        self.comboBox_role.setItemText(1, _translate("Dialog", "用户"))
        self.buttonBox_OK.setText(_translate("Dialog", "确定"))
        self.buttonBox_Cancel.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
