# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0.dev2404081550
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.serverAddress = QtWidgets.QLineEdit(parent=Form)
        self.serverAddress.setGeometry(QtCore.QRect(80, 50, 240, 30))
        self.serverAddress.setObjectName("serverAddress")
        self.username = QtWidgets.QLineEdit(parent=Form)
        self.username.setGeometry(QtCore.QRect(80, 100, 240, 30))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setGeometry(QtCore.QRect(80, 150, 240, 30))
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.loginButton = QtWidgets.QPushButton(parent=Form)
        self.loginButton.setGeometry(QtCore.QRect(80, 200, 100, 30))
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setGeometry(QtCore.QRect(220, 200, 100, 30))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "NekoERP - 登录"))
        self.serverAddress.setPlaceholderText(_translate("Form", "服务器地址"))
        self.username.setPlaceholderText(_translate("Form", "用户名"))
        self.password.setPlaceholderText(_translate("Form", "密码"))
        self.loginButton.setText(_translate("Form", "登录"))
        self.exitButton.setText(_translate("Form", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
